### ISSUE TITLE
Failure migrations marks as successful

### ISSUE THREAD

**Issue by GordeevArt** [dcardon/play-migrate#5]
I use one db - *PostgreSQL 9.2.9*

For example, the migration script may be file with name **13.up.failure_test.sql** with line: **SELECT 1 FROM a;**. *Table `a` does not exist*.

Output:
> ~/play1-1.2.7.2/play migrate:up
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.2.7.2, http://www.playframework.org
~
~ Database migration:
~ 
~    Database: umbrella_mastodon (Alias:db1)
Execution: psql -U postgres -h 10.65.67.232 -p 5432 -t -d umbrella_mastodon -f /data/projects/umbrella/tmp/migrate.module/check_version.sql
~    Version: 12
~    Status: | Successful
~    Max patch version: 13
~ 
~    Migrating...
Execution: psql -U postgres -h 10.65.67.232 -p 5432 -t -d umbrella_mastodon -f /data/projects/umbrella/db/migrate/db1/13.up.failure_test.sql
~      13...
Execution: psql -U postgres -h 10.65.67.232 -p 5432 -t -d umbrella_mastodon -f /data/projects/umbrella/tmp/migrate.module/update_version.sql
~ 
~    Migration completed successfully
~ 
~ ------------------------------------
~

**Comment by dcardon** [comment]
You will need to modify your `migrate.module.file.format` property to tell postgres to stop on errors:

```
migrate.module.file.format=psql -U %(username)s -h %(host)s -P%(port)s --set=ON_ERROR_STOP=on -t -d %(dbname)s -f %(filename)s
```

I've updated the documentation to include this variable setting.

**Comment by GordeevArt** [comment]
Yes, it's work. Thank u!

(In PostgreSQL port defined in lower case: _-p%(port)s_)
